import { PENDING_AUTH_ACTION_KEY, PROMO_CODE_STORAGE_KEY } from '../config/funnel'

export function storePendingAuthAction(action) {
  try {
    sessionStorage.setItem(PENDING_AUTH_ACTION_KEY, JSON.stringify(action))
  } catch {
    /* ignore */
  }
}

export function consumePendingAuthAction() {
  try {
    const raw = sessionStorage.getItem(PENDING_AUTH_ACTION_KEY)
    sessionStorage.removeItem(PENDING_AUTH_ACTION_KEY)
    return raw ? JSON.parse(raw) : null
  } catch {
    return null
  }
}

export function storePromoCode(code) {
  try {
    sessionStorage.setItem(PROMO_CODE_STORAGE_KEY, code)
  } catch {
    /* ignore */
  }
}

export function getStoredPromoCode() {
  try {
    return sessionStorage.getItem(PROMO_CODE_STORAGE_KEY) || ''
  } catch {
    return ''
  }
}

export function downloadTextFile(filename, content) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function buildLabReportMarkdown({ lab, code, output, passed = true }) {
  const now = new Date().toISOString()
  return `# IOAI Lab Report — ${lab?.title || 'Lab session'}

**Date:** ${now}
**Status:** ${passed ? 'Checkpoint passed ✓' : 'In progress'}
**Lab:** ${lab?.subtitle || ''}

## Student code

\`\`\`python
${code?.trim() || '# (empty)'}
\`\`\`

## Console output

\`\`\`
${output?.trim() || '(no output)'}
\`\`\`

---
Generated by Bingo AI Academy · IOAI Training Lab
`
}
