/** Seed data for showcase_cases (from Showcase.jsx fallbacks) */

export const SHOWCASE_AWARD_CASES = [
  { student: 'Student A', grade: 'Grade 6 · Primary', pain: "Zero AI background · didn't know which competition to enter", path: 'AI Literacy Camp → Prestigious Competition Bootcamp → 1-on-1 Coach Prep', result: '🥇 National Prestigious Competition · 1st Prize', duration: '6 months', tags: ['AI Zero Background', 'Prestigious Competition', 'Primary School'], detail: 'Starting from zero, A completed the AI Literacy programme in 2 months, joined the Prestigious Competition Bootcamp, and worked with a competition coach on mock defences. Scored in the top 3% nationally.', type: 'competition' },
  { student: 'Student B', grade: 'Grade 10 · High School', pain: 'Had AI skills but no competition experience or formal results', path: 'ML Intro Camp → Competition Research Project → Pre-Competition Sprint', result: '🥈 Provincial AI Innovation Competition · 2nd Prize', duration: '8 months', tags: ['ML Skills', 'Competition Research', 'High School'], detail: 'B had basic Python skills. With guided research project mentorship and a personalised competition strategy, achieved provincial 2nd place and built a strong comprehensive-evaluation portfolio.', type: 'competition' },
  { student: 'Student C', grade: 'Grade 8 · Middle School', pain: "Parents wanted competitions but didn't know AI education pathway", path: 'AI Literacy → Robotics Camp → Robotics Competition', result: '🏆 City Robotics Championship · Champion', duration: '5 months', tags: ['Robotics', 'Middle School', 'Competition'], detail: 'Complete beginner at entry. Intensive robotics programme with team collaboration training. Won city championship and was invited to join the school robotics team.', type: 'competition' },
]

export const SHOWCASE_ADMISSIONS_CASES = [
  { student: 'Student D', grade: 'Grade 12 · High School', pain: 'Wanted STEM specialty admission but had no qualifying AI results', path: 'Comprehensive Evaluation Research Project → AI Portfolio → STEM Specialty Application', result: '🎓 STEM Specialty Admission · Key Provincial High School', duration: '10 months', tags: ['Comprehensive Evaluation', 'STEM Specialty', 'High School'], detail: 'D used our ML research project as the cornerstone of their comprehensive evaluation application. Research report, competition certificates, and mentor recommendation letter all contributed to a successful STEM specialty offer.', type: 'admissions' },
  { student: 'Student E', grade: 'Grade 11 · High School', pain: 'Strong AI interest but no formal pathway or documentation', path: 'AI Agent Research → Competition Entry → Strong Foundation Application', result: '🎓 Strong Foundation Programme Shortlisted · CS Major · Top-10 University', duration: '12 months', tags: ['Strong Foundation Programme', 'University Application', 'AI Research'], detail: 'E built an AI agent prototype and competed in two national competitions. The working prototype was demonstrated in the strong-foundation interview, directly supporting the CS major shortlisting.', type: 'admissions' },
  { student: 'Student F', grade: 'Grade 12 · International Track', pain: 'Applying to US universities without standout STEM projects', path: 'Data Science Camp → Research Project → International Application', result: '🌏 US University Early Decision · Top-50 School', duration: '8 months', tags: ['International', 'US Admissions', 'Data Science'], detail: '"Impressive depth of STEM project work" — cited directly by admissions letter. Data science portfolio and competition certificate formed the core of the application.', type: 'admissions' },
]

export const SHOWCASE_ABILITY_CASES = [
  { student: 'Student G', grade: 'Grade 5 · Primary', pain: 'Worried child would only use AI tools, not think creatively', path: 'AI Literacy Starter → AIGC Creative Design → Project Portfolio', result: '🎨 AI Art Portfolio · 12 original works · School Exhibition', improvement: ['Creative Thinking +85%', 'Tool Application +90%', 'Self-directed Learning +70%'], type: 'ability' },
  { student: 'Student H', grade: 'Grade 7 · Middle School', pain: 'Child used AI passively — copy-paste mentality', path: 'AI Literacy + Unplugged Science → Data Analysis Project', result: '📊 School Data Science Project Award · District 1st', improvement: ['Logical Thinking +78%', 'Data Literacy +92%', 'Problem Solving +80%'], type: 'ability' },
  { student: 'Student I', grade: 'Grade 9 · Middle School', pain: "Wanted to learn AI but couldn't focus or stay consistent", path: 'AI Foundations → Check-In Programme → ML Intro', result: '🧠 AI Literacy Level 3 Certificate · Competition Portfolio Started', improvement: ['Consistency Score +88%', 'AI Concepts Mastery +82%', 'Confidence +75%'], type: 'ability' },
]
