/**
 * Assessment Center catalog (structure aligned with bingoacademy.cn/assessment)
 */

export const ASSESSMENT_STORAGE_KEY = 'bingo-assessment-records'

/** @typedef {'course' | 'cross'} AssessmentCategory */

export const ASSESSMENT_CATALOG = [
  {
    id: 'l3-course-a',
    title: 'L3 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L3',
    variant: 'A',
    gradeHint: 'L3 course placement',
    desc: 'L3 AI knowledge check (Form A) for students enrolling in the L3 course.',
    questionBank: 'innovation',
    questionCount: 10,
    durationMin: 40,
  },
  {
    id: 'l3-course-b',
    title: 'L3 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L3',
    variant: 'B',
    gradeHint: 'L3 course placement',
    desc: 'L3 AI knowledge check (Form B) for students enrolling in the L3 course.',
    questionBank: 'innovation',
    questionCount: 10,
    durationMin: 40,
  },
  {
    id: 'l1-l3-rec-a',
    title: 'L1–L3 Placement Assessment (Course Recommendation) — Form A',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L1-L3',
    variant: 'A',
    gradeHint: 'Pre-K — Grade 3',
    desc: 'Cross-level L1–L3 placement (Form A) for course recommendations (pre-K through grade 3).',
    questionBank: 'literacy',
    questionCount: 11,
    durationMin: 45,
  },
  {
    id: 'l1-l3-rec-b',
    title: 'L1–L3 Placement Assessment (Course Recommendation) — Form B',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L1-L3',
    variant: 'B',
    gradeHint: 'Pre-K — Grade 3',
    desc: 'Cross-level L1–L3 placement (Form B) for course recommendations (pre-K through grade 3).',
    questionBank: 'literacy',
    questionCount: 11,
    durationMin: 45,
  },
  {
    id: 'l1-l3-rec-c',
    title: 'L1–L3 Placement Assessment (Course Recommendation) — Form C',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L1-L3',
    variant: 'C',
    gradeHint: 'Pre-K — Grade 3',
    desc: 'Cross-level L1–L3 placement (Form C) for course recommendations (pre-K through grade 3).',
    questionBank: 'basic',
    questionCount: 8,
    durationMin: 20,
  },
  {
    id: 'l2-course-a',
    title: 'L2 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L2',
    variant: 'A',
    gradeHint: 'L2 course placement',
    desc: 'L2 AI knowledge check (Form A) for students enrolling in the L2 course.',
    questionBank: 'literacy',
    questionCount: 11,
    durationMin: 45,
  },
  {
    id: 'l2-course-b',
    title: 'L2 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L2',
    variant: 'B',
    gradeHint: 'L2 course placement',
    desc: 'L2 AI knowledge check (Form B) for students enrolling in the L2 course.',
    questionBank: 'literacy',
    questionCount: 11,
    durationMin: 45,
  },
  {
    id: 'l1-course-a',
    title: 'L1 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L1',
    variant: 'A',
    gradeHint: 'L1 course placement',
    desc: 'L1 AI knowledge check (Form A) for students enrolling in the L1 course.',
    questionBank: 'basic',
    questionCount: 8,
    durationMin: 20,
  },
  {
    id: 'l1-course-b',
    title: 'L1 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L1',
    variant: 'B',
    gradeHint: 'L1 course placement',
    desc: 'L1 AI knowledge check (Form B) for students enrolling in the L1 course.',
    questionBank: 'basic',
    questionCount: 8,
    durationMin: 20,
  },
  {
    id: 'l4-course-a',
    title: 'L4 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L4',
    variant: 'A',
    gradeHint: 'L4 course placement',
    desc: 'L4 AI knowledge check (Form A) for students enrolling in the L4 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l4-course-b',
    title: 'L4 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L4',
    variant: 'B',
    gradeHint: 'L4 course placement',
    desc: 'L4 AI knowledge check (Form B) for students enrolling in the L4 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l5-course-a',
    title: 'L5 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L5',
    variant: 'A',
    gradeHint: 'L5 course placement',
    desc: 'L5 AI knowledge check (Form A) for students enrolling in the L5 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l5-course-b',
    title: 'L5 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L5',
    variant: 'B',
    gradeHint: 'L5 course placement',
    desc: 'L5 AI knowledge check (Form B) for students enrolling in the L5 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l6-course-a',
    title: 'L6 Course Knowledge Assessment — Form A',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L6',
    variant: 'A',
    gradeHint: 'L6 course placement',
    desc: 'L6 AI knowledge check (Form A) for students enrolling in the L6 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l6-course-b',
    title: 'L6 Course Knowledge Assessment — Form B',
    priceOriginal: 199,
    free: true,
    category: 'course',
    level: 'L6',
    variant: 'B',
    gradeHint: 'L6 course placement',
    desc: 'L6 AI knowledge check (Form B) for students enrolling in the L6 course.',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l4-l6-rec-a',
    title: 'L4–L6 Placement Assessment (Course Recommendation) — Form A',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L4-L6',
    variant: 'A',
    gradeHint: 'Grades 3–6',
    desc: 'Cross-level L4–L6 placement (Form A) for course recommendations (grades 3–6).',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l4-l6-rec-b',
    title: 'L4–L6 Placement Assessment (Course Recommendation) — Form B',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L4-L6',
    variant: 'B',
    gradeHint: 'Grades 3–6',
    desc: 'Cross-level L4–L6 placement (Form B) for course recommendations (grades 3–6).',
    questionBank: 'coding',
    questionCount: 12,
    durationMin: 60,
  },
  {
    id: 'l4-l6-rec-c',
    title: 'L4–L6 Placement Assessment (Course Recommendation) — Form C',
    priceOriginal: 299,
    free: true,
    category: 'cross',
    level: 'L4-L6',
    variant: 'C',
    gradeHint: 'Grades 3–6',
    desc: 'Cross-level L4–L6 placement (Form C) for course recommendations (grades 3–6).',
    questionBank: 'innovation',
    questionCount: 10,
    durationMin: 40,
  },
]

export const ASSESSMENT_GROUPS = [
  { id: 'l3', label: 'L3 course knowledge', filter: (a) => a.level === 'L3' && a.category === 'course' },
  { id: 'l1-l3', label: 'L1–L3 placement', filter: (a) => a.level === 'L1-L3' },
  { id: 'l2', label: 'L2 course knowledge', filter: (a) => a.level === 'L2' && a.category === 'course' },
  { id: 'l1', label: 'L1 course knowledge', filter: (a) => a.level === 'L1' && a.category === 'course' },
  { id: 'l4', label: 'L4 course knowledge', filter: (a) => a.level === 'L4' && a.category === 'course' },
  { id: 'l5', label: 'L5 course knowledge', filter: (a) => a.level === 'L5' && a.category === 'course' },
  { id: 'l6', label: 'L6 course knowledge', filter: (a) => a.level === 'L6' && a.category === 'course' },
  { id: 'l4-l6', label: 'L4–L6 placement', filter: (a) => a.level === 'L4-L6' },
]

export function getAssessmentById(id) {
  return ASSESSMENT_CATALOG.find((a) => a.id === id) ?? null
}

export function formatPriceLabel(paper) {
  if (paper.free) {
    return { original: `$${paper.priceOriginal}`, show: 'Free' }
  }
  return { original: `$${paper.priceOriginal}`, show: `$${paper.priceOriginal}` }
}
