/** Copy for the Amazon-style /checkout review page */

export const CHECKOUT_PAGE = {
  title: 'Secure checkout',
  documentTitle: 'Secure checkout | Bingo Academy',
  cart: 'Back',
  accountHeading: 'Account',
  signedInAs: 'Signed in as',
  changeAccount: 'Change',
  itemsHeading: 'Review your order',
  digitalDelivery: 'Digital access — unlocks in your Study Center after payment',
  paymentHeading: 'Payment',
  payWithStripe: 'You’ll pay securely with Stripe on the next step.',
  promoLink: 'Use a gift card, voucher, or promo code',
  promoHide: 'Hide promo code',
  promoPlaceholder: 'Enter Code',
  promoMinCheckoutApplied: 'Minimum charge for this promo code: $1.00',
  placeOrder: 'Place your order',
  placingOrder: 'Continuing to payment…',
  legal:
    'By placing your order, you agree to Bingo Academy’s terms of use and privacy policy. Digital course access is delivered immediately after successful payment.',
  summaryHeading: 'Order summary',
  itemsLabel: (n) => `Items (${n}):`,
  promoLabel: 'Promo',
  orderTotal: 'Order total:',
  emptyTitle: 'Nothing to check out',
  emptyDesc: 'Choose a course unit or bundle, then return here to complete your purchase.',
  browseCourses: 'Browse courses',
  loadError: 'Could not load this order. Go back and try again.',
  kindUnit: 'Course unit',
  kindAddon: 'Add-on',
  kindBundle: 'Bundle',
  kindCourse: 'Course',
  kindItem: 'Item',
}
