/** Copy for /courses page */

export const COURSES_PORTAL = {
  bannerEyebrow: 'AI Course Center',
  browseCourses: 'Browse courses',
  assessmentChip: 'Assessment · Find your path',
  labChip: 'Labs & kits',
  explorationChip: 'AI Exploration · free games',
  ioaiFeaturedLabel: 'IOAI Featured',
  ioaiFeaturedTitle: 'Whitelist competition training · Enrolling now',
  ioaiFeaturedDesc:
    'The IOAI Competition Course System (11 modules · 110 lessons) is live — foundation, core ML/DL, CV/NLP/RL tracks, and national-team sprint prep.',
  comingSoonHint:
    'Self-study / classroom items marked “Coming soon” — try AI Exploration free or browse product labs.',
  allTypes: 'All types',
  courseCount: (n) => `${n} course${n === 1 ? '' : 's'}`,
  emptyCategory: 'No courses in this category yet. Check back soon.',
  comingSoonBadge: 'Coming soon',
  viewDetails: 'View details',
  materialsMall: 'Materials store',
  certTitle: 'Bingo AI Academy Certification',
  certDesc: 'Earn capability certificates after courses and Lab tasks — verifiable on the official site.',
  certCta: 'Certification center →',
  notFound: 'Course not found',
  backToCourses: 'Back to course center',
  backTo: 'Back to',
  statusComingSoon: 'Coming soon',
  statusEnrolling: 'Enrolling now',
  audience: 'Who it\'s for',
  outcomes: 'Learning outcomes',
  syllabus: 'Syllabus',
  linkedLabs: 'Optional AI Exploration games',
  linkedLabsDesc: 'Free browser games — optional, not the same as product labs or kits',
  enrollCta: 'Unlock Full Lesson',
  continueLearning: 'Continue in Study Center',
  viewFullTrack: 'View full IOAI track',
  freeAssessment: 'Free placement assessment',
  materialsCta: 'Materials & lab kits',
  enrollNow: 'Enroll Now',
  contactSales: 'Contact sales',
  videoPreviewBadge: 'Free preview',
  videoFullBadge: 'Full lesson',
  previewLength: (sec) => `${sec}s preview`,
  previewCutoff: (sec) => `Preview ends at ${sec}s`,
  previewLabel: 'preview',
  previewUpgradeHint: 'Unlock to watch the full lesson',
  watchPreview: 'Watch free preview',
  replayPreview: 'Replay preview',
  previewEndedTitle: 'Preview ended',
  previewEndedDesc:
    'You watched the free sample. Unlock this lesson or get the IOAI Full Track for all 110 lessons.',
  unlockTitle: 'Get full access',
  unlockDesc: 'Watch the complete lesson, download notes, and track progress in your Study Center.',
  singleLesson: 'This lesson',
  singleLessonDesc: 'Lifetime access to this video lesson and checkpoints.',
  fullTrack: 'IOAI Full Track',
  fullTrackDesc: 'All 110 lessons · 11 modules · mock contests & national-team prep.',
  fromPrice: (n) => `From $${n.toLocaleString()}`,
  unlockLesson: (price) => `Unlock This Lesson — $${price}`,
  unlockLessonShort: 'Unlock full lesson',
  unlockTrack: 'Get IOAI Full Track',
  trackOwned: 'Full track in your library',
  accessUnlockedTitle: 'You have full access',
  accessUnlockedDesc: 'Resume anytime from Study Center. Your progress is saved automatically.',
  signInHint: 'Sign in to sync purchases across devices.',
  signIn: 'Sign in',
  signInHintSuffix: '(Demo unlock works without payment.)',
  demoPurchaseNote: 'Demo mode: purchases unlock instantly. Stripe checkout coming soon.',
  stripeCheckoutNote: 'Secure payment via Stripe Checkout. Access unlocks automatically after payment.',
  searchPlaceholder: 'Search courses…',
  sortLabel: 'Sort:',
  filterCategory: 'Topic',
  filterLevel: 'Level',
  filterPrice: 'Price',
  emptyFilterTitle: 'No courses match your filters',
  emptyFilterDesc: 'Try clearing filters or search with different keywords.',
  clearFilters: 'Clear all filters',
  statCourses: 'Courses',
  statStudents: 'Students',
  statRating: 'Avg. rating',
  videoListSubtitle: (lineId) => {
    const map = {
      general: 'Explore self-paced AI video courses — literacy, tools, and creative projects for independent learners.',
      ioai: 'IOAI Competition Course System — 11 modules · 110 video lessons from foundations to national-team selection prep.',
      k12: 'Classroom-ready AI video courses for schools — aligned packs with teacher support.',
    }
    return map[lineId] || map.general
  },
}
