/**
 * Full course catalogue — IOAI priority; self-study & classroom marked coming-soon.
 * @typedef {'live' | 'coming-soon'} CourseStatus
 * @typedef {'video' | 'camp' | 'self-study' | 'classroom' | 'lab' | 'materials' | 'books'} DeliveryType
 */

import { buildIOAIVideoCatalogEntries } from './ioaiCourseSystem.js'

export const COURSE_STATUS = {
  LIVE: 'live',
  COMING_SOON: 'coming-soon',
}

/** Legacy IOAI video slugs replaced by the 110-lesson competition system */
const REPLACED_IOAI_VIDEO_IDS = new Set([
  'ioai-whitelist',
  'ioai-aigc-sprint',
  'ioai-mock',
  'i1',
  'i2',
])

const LEGACY_COURSE_CATALOG = [
  {
    id: 'ioai-whitelist',
    line: 'ioai',
    sub: 'video',
    status: 'live',
    deliveryType: 'video',
    featured: true,
    name: 'IOAI Whitelist Competition Full Track',
    nameEn: 'IOAI Whitelist Competition Full Track',
    desc: 'End-to-end prep for IOAI and similar whitelist AI innovation competitions: topic, proposal, prototype, defence, and mock judging.',
    price: 'From $1,250',
    hours: '32 sessions · 6-month enrolment',
    badge: 'IOAI Featured',
    outcomes: [
      'Understand IOAI problem formats and scoring',
      'Deliver a defensible project prototype and documentation',
      'Complete two mock defences with mentor feedback',
    ],
    audience: 'Grades 7–12 · Python or block coding background helpful',
    syllabus: [
      'Problem analysis & past award case studies',
      'AI innovation topic selection & feasibility',
      'AIGC / multimodal prototype labs',
      'Technical report & defence deck polish',
      'Mock whitelist defence (mentor review)',
    ],
    labSlugs: ['doodle-monsters', 'evolve-car', 'jailbreak-adventure'],
  },
  {
    id: 'ioai-aigc-sprint',
    line: 'ioai',
    sub: 'video',
    status: 'live',
    deliveryType: 'video',
    featured: true,
    name: 'AIGC Innovation Sprint (Video)',
    nameEn: 'AIGC Innovation Sprint',
    desc: 'Generative-AI competition track: prompt engineering, storytelling, compliance, and presentation.',
    price: '$699',
    hours: '16 sessions',
    badge: 'Video course',
    outcomes: [
      'Submit a competition-ready AIGC entry',
      'Document process and artist statement',
      'Understand judging criteria for creativity and completeness',
    ],
    audience: 'Upper elementary — high school',
    syllabus: ['AIGC toolchain & entry rules', 'Creative brief & storyboard', 'Quality control', 'Packaging & online submission'],
    labSlugs: ['word-gravity', 'doodle-monsters'],
  },
  {
    id: 'ioai-camp',
    line: 'ioai',
    sub: 'online-lab',
    status: 'live',
    deliveryType: 'camp',
    name: 'IOAI Winter / Summer Training Camp',
    nameEn: 'IOAI Training Camp',
    desc: 'Small-group camp with daily project checkpoints and finale mock competition — ideal 4–8 weeks before deadlines.',
    price: '$690 / session',
    hours: '10 days · 3h/day',
    badge: 'Training camp',
    outcomes: [
      'Finish one submittable project in camp',
      '1:1 topic review with mentor',
      'Parent showcase on defence day',
    ],
    audience: 'Grades 7–12',
    syllabus: [
      'Opening assessment & topic lock-in',
      'Build sprints & daily stand-ups',
      'Mock defence day',
      'Post-camp review & portfolio tips',
    ],
    labSlugs: ['evolve-car', 'hide-and-seek', 'virtual-conductor'],
  },
  {
    id: 'ioai-mock',
    line: 'ioai',
    sub: 'video',
    status: 'live',
    deliveryType: 'video',
    name: 'IOAI Mock Competition & Defence Workshop',
    nameEn: 'Mock Competition & Defence Workshop',
    desc: 'Simulated judging, timed defence, and Q&A drills.',
    price: '$279',
    hours: '6 sessions + 2 mock rounds',
    badge: 'Sprint',
    outcomes: ['Confident defence pacing', 'Written judge feedback'],
    audience: 'Students with a draft project',
    syllabus: ['Rubric breakdown', 'Defence round 1', 'Revision guidance', 'Defence round 2'],
    labSlugs: ['jailbreak-adventure'],
  },
  {
    id: 'g-literacy',
    line: 'general',
    sub: 'course',
    status: 'coming-soon',
    deliveryType: 'self-study',
    name: 'AI Literacy Self-Study (L1–L3)',
    nameEn: 'AI Literacy Self-Study',
    desc: 'Family-friendly self-paced track: AI basics, ethics, tools, and mini projects with check-ins and auto-assessment.',
    price: 'Coming soon',
    hours: '12 weeks · self-paced',
    badge: 'Self-study',
    outcomes: ['AI literacy knowledge framework', '6+ small project artefacts'],
    audience: 'Grades 3–9',
    syllabus: ['Coming soon: chapters and lab checklist in progress'],
    labSlugs: ['doodle-monsters', 'hide-and-seek'],
  },
  {
    id: 'g-lab-pack',
    line: 'general',
    sub: 'online-lab',
    status: 'coming-soon',
    deliveryType: 'self-study',
    name: 'Cloud Lab Self-Study Pack',
    nameEn: 'Cloud Lab Self-Study Pack',
    desc: 'Task sheets linked to AI Exploration Lab with auto-grading.',
    price: 'Coming soon',
    hours: '8 lab units',
    badge: 'Self-study labs',
    outcomes: ['Learn ML concepts through game-like labs'],
    audience: 'All ages',
    syllabus: ['Coming soon'],
    labSlugs: ['word-gravity', 'evolve-car', 'doodle-monsters'],
  },
  {
    id: 'g1',
    line: 'general',
    sub: 'course',
    status: 'live',
    deliveryType: 'video',
    name: 'AI Literacy Foundations',
    desc: 'Core AI concepts, ethics, and creative thinking — introductory track (content expanding).',
    price: '$299',
    hours: '12 sessions',
    badge: 'General',
    outcomes: ['Understand core AI concepts', 'Complete introductory creative projects'],
    audience: 'Ages 10+',
    syllabus: ['What is AI?', 'AI in daily life', 'Ethics & creativity', 'Mini project'],
    labSlugs: ['hide-and-seek'],
  },
  {
    id: 'g3',
    line: 'general',
    sub: 'materials-pack',
    status: 'live',
    deliveryType: 'materials',
    name: 'Home Experiment Materials Pack',
    desc: 'Digital guides + consumables for general AI labs.',
    price: '$128',
    hours: 'Kit',
    badge: 'Materials',
    outcomes: ['Hands-on home experiments'],
    audience: 'Families',
    syllabus: ['Kit unboxing & safety', 'Guided experiments'],
    labSlugs: [],
  },
  {
    id: 'k-classroom',
    line: 'k12',
    sub: 'course',
    status: 'coming-soon',
    deliveryType: 'classroom',
    name: 'K12 Classroom AI Course Pack',
    nameEn: 'K12 Classroom AI Course Pack',
    desc: 'Teacher guides, slides, classroom activities, and term assessments — school deployment edition launching soon.',
    price: 'School quote',
    hours: 'Full term',
    badge: 'Classroom',
    outcomes: ['Unified school pacing', 'Class labs aligned to assessments'],
    audience: 'Schools · grades 3–9',
    syllabus: ['Coming soon: grade-banded teacher packs'],
    labSlugs: ['doodle-monsters', 'evolve-car'],
  },
  {
    id: 'k1',
    line: 'k12',
    sub: 'books',
    status: 'live',
    deliveryType: 'books',
    name: 'AI Literacy Textbook Series (Grades 3–9)',
    desc: 'Aligned classroom textbooks — digital and print.',
    price: '$128',
    hours: '7 volumes',
    badge: 'Books',
    outcomes: ['Curriculum-aligned literacy'],
    audience: 'Schools',
    syllabus: ['Grade-banded units'],
    labSlugs: [],
  },
  {
    id: 'k3',
    line: 'k12',
    sub: 'online-lab',
    status: 'live',
    deliveryType: 'lab',
    name: 'Classroom Online Lab License',
    desc: 'Whole-class cloud lab with teacher dashboard.',
    price: '$12,800/yr',
    hours: 'School',
    badge: 'Online Lab',
    outcomes: ['Class-wide lab access'],
    audience: 'Schools',
    syllabus: ['Teacher onboarding', 'Class lab sessions'],
    labSlugs: ['word-gravity', 'evolve-car'],
  },
  {
    id: 'i1',
    line: 'ioai',
    sub: 'video',
    status: 'live',
    deliveryType: 'video',
    name: 'AIGC Whitelist Competition Course',
    desc: 'IOAI-oriented video lessons with progress tracking — see ioai-aigc-sprint for full syllabus.',
    price: '$890',
    hours: '16+ sessions',
    badge: 'IOAI',
    outcomes: ['Competition-ready AIGC portfolio'],
    audience: 'Middle & high school',
    syllabus: ['Legacy track — redirects to updated IOAI sprint content'],
    labSlugs: ['doodle-monsters'],
  },
  {
    id: 'i2',
    line: 'ioai',
    sub: 'video',
    status: 'live',
    deliveryType: 'video',
    name: 'Competition Sprint Video Series',
    desc: 'Topic selection, project build, and presentation skills.',
    price: '$999',
    hours: '16 sessions',
    badge: 'Video',
    outcomes: ['Structured competition project'],
    audience: 'Middle & high school',
    syllabus: ['Topic · Build · Present'],
    labSlugs: ['evolve-car'],
  },
  {
    id: 'i3',
    line: 'ioai',
    sub: 'online-lab',
    status: 'live',
    deliveryType: 'camp',
    name: 'IOAI Competition Training Camp',
    desc: 'See ioai-camp for the latest camp schedule.',
    price: '$490',
    hours: '10 sessions',
    badge: 'Training Camp',
    outcomes: ['Camp project completion'],
    audience: 'Competition track',
    syllabus: ['Camp format'],
    labSlugs: ['evolve-car', 'hide-and-seek'],
  },
  {
    id: 'g2',
    line: 'general',
    sub: 'online-lab',
    status: 'coming-soon',
    deliveryType: 'self-study',
    name: 'Cloud AI Exploration Lab',
    desc: 'Guided online experiments — bundling with Lab module.',
    price: '$199',
    hours: '8 labs',
    badge: 'Online Lab',
    outcomes: ['Lab-based literacy'],
    audience: 'Self-learners',
    syllabus: ['Coming soon'],
    labSlugs: ['word-gravity', 'jailbreak-adventure', 'doodle-monsters'],
  },
  {
    id: 'k2',
    line: 'k12',
    sub: 'course',
    status: 'coming-soon',
    deliveryType: 'classroom',
    name: 'K12 Classroom AI Course Pack',
    desc: 'Teacher slides, worksheets, and term plans.',
    price: 'Quote',
    hours: 'Full term',
    badge: 'Course',
    outcomes: ['Classroom delivery'],
    audience: 'Schools',
    syllabus: ['Coming soon'],
    labSlugs: [],
  },
  {
    id: 'k4',
    line: 'k12',
    sub: 'materials-pack',
    status: 'live',
    deliveryType: 'materials',
    name: 'Class Lab Materials Pack (30 students)',
    desc: 'Per-class consumables and digital bundle.',
    price: '$2,980',
    hours: 'Bulk',
    badge: 'Materials',
    outcomes: ['Class lab supplies'],
    audience: 'Schools',
    syllabus: ['Bulk kit guide'],
    labSlugs: [],
  },
  {
    id: 'k5',
    line: 'k12',
    sub: 'offline-lab',
    status: 'live',
    deliveryType: 'classroom',
    name: 'Offline AI Lab Setup',
    desc: 'Hardware layout, safety, and lesson integration.',
    price: 'Quote',
    hours: 'On-site',
    badge: 'Offline Lab',
    outcomes: ['On-site lab readiness'],
    audience: 'Schools',
    syllabus: ['Site planning'],
    labSlugs: [],
  },
  {
    id: 'k6',
    line: 'k12',
    sub: 'school-kit',
    status: 'live',
    deliveryType: 'materials',
    name: 'Institution Offline Lab Kits',
    desc: 'Bulk offline lab kits for classrooms.',
    price: 'Quote',
    hours: 'Bulk',
    badge: 'Offline Lab Kits',
    outcomes: ['Institutional rollout'],
    audience: 'Schools',
    syllabus: ['Kit deployment'],
    labSlugs: [],
  },
]

export const IOAI_VIDEO_COURSES = buildIOAIVideoCatalogEntries()

/** @type {Array<object>} */
export const COURSE_CATALOG = [
  ...IOAI_VIDEO_COURSES,
  ...LEGACY_COURSE_CATALOG.filter(
    (c) => !(c.line === 'ioai' && c.sub === 'video' && REPLACED_IOAI_VIDEO_IDS.has(c.id))
  ),
]

export function getCourseById(id) {
  return COURSE_CATALOG.find((c) => c.id === id) ?? null
}

export function isCourseComingSoon(course) {
  return course?.status === COURSE_STATUS.COMING_SOON
}

export function coursesByLine(lineId, { featuredOnly = false } = {}) {
  let list = COURSE_CATALOG.filter((c) => c.line === lineId)
  if (featuredOnly) list = list.filter((c) => c.featured)
  return list
}
