/** Student portfolio highlights — visual-first showcase */

export const PORTFOLIO_CATEGORIES = [
  { id: 'all', label: 'All works' },
  { id: 'aigc', label: 'AIGC' },
  { id: 'ml', label: 'Machine learning' },
  { id: 'robotics', label: 'Robotics / hardware' },
  { id: 'research', label: 'Research' },
]

export const STUDENT_PORTFOLIO = [
  {
    id: 'p1',
    title: 'Campus Waste-Sorting Vision Assistant',
    student: 'Student Chen · Grade 8',
    category: 'ml',
    track: 'IOAI provincial · 2nd prize',
    year: 2025,
    gradient: 'from-cyan-500 to-blue-700',
    emoji: '♻️',
    tags: ['Computer vision', 'Python', 'IOAI'],
    blurb: 'Custom dataset + MobileNet fine-tuning; 91% accuracy in school pilot.',
    link: '/showcase/works',
  },
  {
    id: 'p2',
    title: 'AI Picture Book — Journey of the Stars',
    student: 'Student Li · Grade 5',
    category: 'aigc',
    track: 'City AIGC creative award',
    year: 2025,
    gradient: 'from-violet-500 to-fuchsia-600',
    emoji: '📖',
    tags: ['AIGC', 'Storyboard', 'Elementary'],
    blurb: '12-page original book with process docs and ethics notes.',
    link: '/showcase/works',
  },
  {
    id: 'p3',
    title: 'Multimodal Emotion Companion Prototype',
    student: 'Student Wang · Grade 10',
    category: 'research',
    track: 'STEM comprehensive eval portfolio',
    year: 2024,
    gradient: 'from-amber-400 to-orange-600',
    emoji: '🧠',
    tags: ['Multimodal', 'Research log', 'Admissions'],
    blurb: 'Voice + vision fusion with full lab notes and defence video.',
    link: '/showcase/works',
  },
  {
    id: 'p4',
    title: 'Maze Navigation Rover (RL Demo)',
    student: 'Student Zhang · Grade 7',
    category: 'robotics',
    track: 'District robotics champion',
    year: 2025,
    gradient: 'from-emerald-500 to-teal-700',
    emoji: '🤖',
    tags: ['Robotics', 'RL concepts', 'Team event'],
    blurb: 'Physical maze challenge inspired by Lab Evolve! AI Car.',
    link: '/exploration/evolve-car',
  },
  {
    id: 'p5',
    title: 'Dialect Speech Transcription Tool',
    student: 'Student Zhao · Grade 12',
    category: 'ml',
    track: 'Strong-foundation interview demo',
    year: 2024,
    gradient: 'from-slate-600 to-slate-900',
    emoji: '🎙️',
    tags: ['NLP', 'Open source', 'Interview piece'],
    blurb: 'Regional dialect samples + Whisper fine-tune demo site.',
    link: '/showcase/works',
  },
  {
    id: 'p6',
    title: 'AI Art Exhibition Series',
    student: 'Bingo Academy cohort',
    category: 'aigc',
    track: 'School exhibition · 28 pieces',
    year: 2025,
    gradient: 'from-rose-400 to-pink-600',
    emoji: '🎨',
    tags: ['AIGC', 'Portfolio', 'Exhibition'],
    blurb: 'Curated 28 student AI artworks with artist statements.',
    link: '/showcase/works',
  },
]
